services:
  ruleengine:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    environment:
      PORT: "5000"
      HOST: "0.0.0.0"
      POSTGRES: "postgresql://admin:admin@postgres:5432/rules?sslmode=disable"

  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rules
